# Introducción a Pandas: Principales Funciones y Usos

En este Notebook, exploraremos **pandas**, una de las librerías más populares de Python para la manipulación y análisis de datos. Aprenderemos sus principales funciones y cómo usarlas en proyectos reales.

---

## 1. ¿Qué es Pandas?

**Pandas** es una librería de Python diseñada para trabajar con datos tabulares, como hojas de cálculo o bases de datos. Es especialmente útil para:
- Leer y escribir datos en diferentes formatos (CSV, Excel, JSON, etc.).
- Limpiar y transformar datos.
- Realizar análisis estadísticos.
- Visualizar datos (en combinación con otras librerías como Matplotlib o Seaborn).

### Instalación de Pandas
Si no tienes pandas instalado, puedes instalarlo con:
```bash
pip install pandas

In [ ]:
!pip install pandas
!pip install openpyxl

# 2. Principales Estructuras de Datos en Pandas
Pandas tiene dos estructuras principales:

**1. Series:** es una estructura unidimensional, similar a una lista o columna en una tabla.

**2. DataFrame:** es una estructura bidimensional, similar a una tabla con filas y columnas.

# 3. Principales Funciones y Usos de Pandas

### 3.1. Crear un DataFrame

Un DataFrame es la estructura principal de pandas. Podemos crearlo a partir de un diccionario, una lista o leyendo un archivo.

In [10]:
import pandas as pd

datos = pd.DataFrame(
    data={
        "Nombre": ["Juan", "María", "Pedro", "Ana"],
        "Edad": [28, 34, 22, 30],
        "Ciudad": ["Madrid", "Barcelona", "Valencia", "Sevilla"],
    }
)
datos

  Nombre  Edad     Ciudad
0   Juan    28     Madrid
1  María    34  Barcelona
2  Pedro    22   Valencia
3    Ana    30    Sevilla

In [8]:
datos_excel = pd.read_excel("archivo_excel.xlsx")
datos_excel

,orderIdentifier,orderType,vendor.organizationIdentifier,buyer.organizationIdentifier,shipFromInstructionLocation.locationIdentifier,shipToLocation.locationIdentifier,orderStatus,createdDate,requestedShipDate,requestedDeliveryDate,...,quantity,quantityUnits,totalValue,orderValueCurrency,lineCount,totalShippedQuantity,exclude,sourceLink,precio_unitario,precio_unitario_iva
0,100044349,OUTBOUND,LightTree,AHTD,LT-1,AHTD - Bentonville,NaN,2021-06-08T00:00:00,2021-07-20T00:00:00,2021-07-30T00:00:00,...,189,EA,236250,USD,3,NaN,NaN,http://lighttree.com/100044349,1250.000000,1487.500000
1,100044350,OUTBOUND,LightTree,AHTD,LT-1,AHTD - Bentonville,NaN,2021-06-08T00:00:00,2021-07-23T00:00:00,2021-07-30T00:00:00,...,20,EA,25000,USD,3,NaN,NaN,http://lighttree.com/100044350,1250.000000,1487.500000
2,100044353,OUTBOUND,LightTree,AHTD,LT-1,AHTD - Bentonville,NaN,2021-06-08T00:00:00,2021-07-13T00:00:00,2021-07-30T00:00:00,...,212,EA,265000,USD,3,NaN,NaN,http://lighttree.com/100044353,1250.000000,1487.500000
3,100055001,OUTBOUND,LightTree,AHTD,LT-2,AHTD - Bentonville,NaN,2017-07-11T00:00:00,2021-08-10T00:00:00,2021-08-18T00:00:00,...,761,EA,59473,USD,3,NaN,NaN,http://lighttree.com/100055001,78.151117,92.999829
4,100055003,OUTBOUND,LightTree,AHTD,LT-2,AHTD - Bentonville,NaN,2017-07-20T00:00:00,2021-08-11T00:00:00,2021-08-14T00:00:00,...,520,EA,47438,USD,3,NaN,NaN,http://lighttree.com/100055003,91.226923,108.560038
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,100044330,OUTBOUND,LightTree,QPWD,LT-2,QPWD - Ville de Québec,NaN,2021-07-07T00:00:00,2021-08-06T00:00:00,2021-08-12T00:00:00,...,12,EA,15000,USD,3,NaN,NaN,http://lighttree.com/100044330,1250.000000,1487.500000
210,100044331,OUTBOUND,LightTree,QPWD,LT-2,QPWD - Ville de Québec,NaN,2021-07-07T00:00:00,2021-08-04T00:00:00,2021-08-12T00:00:00,...,960,EA,1200000,USD,3,NaN,NaN,http://lighttree.com/100044331,1250.000000,1487.500000
211,100044332,OUTBOUND,LightTree,QPWD,LT-2,QPWD - Ville de Québec,NaN,2021-07-07T00:00:00,2021-08-21T00:00:00,2021-08-27T00:00:00,...,56,EA,70000,USD,3,NaN,NaN,http://lighttree.com/100044332,1250.000000,1487.500000
212,100055004,OUTBOUND,LightTree,QPWD,LT-2,QPWD - Ville de Québec,NaN,2017-07-11T00:00:00,2021-08-10T00:00:00,2021-08-18T00:00:00,...,597,EA,44953,USD,3,NaN,NaN,http://lighttree.com/100055004,75.298157,89.604807
213,100055011,OUTBOUND,LightTree,QPWD,LT-2,QPWD - Ville de Québec,NaN,2017-07-11T00:00:00,2021-08-10T00:00:00,2021-08-18T00:00:00,...,447,EA,27319,USD,4,NaN,NaN,http://lighttree.com/100055011,61.116331,72.728434

### 3.2. Leer un Archivo CSV
Pandas puede leer archivos CSV directamente desde una URL o un archivo local.

In [19]:
datos_csv = pd.read_csv("Order_v3.csv", encoding="latin-1")
datos_csv

,orderIdentifier,orderType,vendor.organizationIdentifier,buyer.organizationIdentifier,shipFromInstructionLocation.locationIdentifier,shipToLocation.locationIdentifier,orderStatus,createdDate,requestedShipDate,requestedDeliveryDate,plannedShipDate,plannedDeliveryDate,quantity,quantityUnits,totalValue,orderValueCurrency,lineCount,totalShippedQuantity,exclude,sourceLink
0,100044349,OUTBOUND,LightTree,AHTD,LT-1,AHTD - Bentonville,NaN,2021-06-08T00:00:00,2021-07-20T00:00:00,2021-07-30T00:00:00,2021-07-23T00:00:00,2021-07-30T00:00:00,189,EA,236250.0,USD,3,NaN,NaN,http://lighttree.com/100044349
1,100044350,OUTBOUND,LightTree,AHTD,LT-1,AHTD - Bentonville,NaN,2021-06-08T00:00:00,2021-07-23T00:00:00,2021-07-30T00:00:00,2021-07-23T00:00:00,2021-07-30T00:00:00,20,EA,25000.0,USD,3,NaN,NaN,http://lighttree.com/100044350
2,100044353,OUTBOUND,LightTree,AHTD,LT-1,AHTD - Bentonville,NaN,2021-06-08T00:00:00,2021-07-13T00:00:00,2021-07-30T00:00:00,2021-07-23T00:00:00,2021-07-30T00:00:00,212,EA,265000.0,USD,3,NaN,NaN,http://lighttree.com/100044353
3,100055001,OUTBOUND,LightTree,AHTD,LT-2,AHTD - Bentonville,NaN,2017-07-11T00:00:00,2021-08-10T00:00:00,2021-08-18T00:00:00,2021-08-10T00:00:00,2021-08-18T00:00:00,761,EA,59473.0,USD,3,NaN,NaN,http://lighttree.com/100055001
4,100055003,OUTBOUND,LightTree,AHTD,LT-2,AHTD - Bentonville,NaN,2017-07-20T00:00:00,2021-08-11T00:00:00,2021-08-14T00:00:00,2021-08-11T00:00:00,2021-08-14T00:00:00,520,EA,47438.0,USD,3,NaN,NaN,http://lighttree.com/100055003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,100044330,OUTBOUND,LightTree,QPWD,LT-2,QPWD - Ville de Québec,NaN,2021-07-07T00:00:00,2021-08-06T00:00:00,2021-08-12T00:00:00,2021-08-06T00:00:00,2021-08-12T00:00:00,12,EA,15000.0,USD,3,NaN,NaN,http://lighttree.com/100044330
210,100044331,OUTBOUND,LightTree,QPWD,LT-2,QPWD - Ville de Québec,NaN,2021-07-07T00:00:00,2021-08-04T00:00:00,2021-08-12T00:00:00,2021-08-06T00:00:00,2021-08-12T00:00:00,960,EA,1200000.0,USD,3,NaN,NaN,http://lighttree.com/100044331
211,100044332,OUTBOUND,LightTree,QPWD,LT-2,QPWD - Ville de Québec,NaN,2021-07-07T00:00:00,2021-08-21T00:00:00,2021-08-27T00:00:00,2021-08-21T00:00:00,2021-08-27T00:00:00,56,EA,70000.0,USD,3,NaN,NaN,http://lighttree.com/100044332
212,100055004,OUTBOUND,LightTree,QPWD,LT-2,QPWD - Ville de Québec,NaN,2017-07-11T00:00:00,2021-08-10T00:00:00,2021-08-18T00:00:00,NaN,NaN,597,EA,44953.0,USD,3,NaN,NaN,http://lighttree.com/100055004
213,100055011,OUTBOUND,LightTree,QPWD,LT-2,QPWD - Ville de Québec,NaN,2017-07-11T00:00:00,2021-08-10T00:00:00,2021-08-18T00:00:00,2021-08-10T00:00:00,2021-08-18T00:00:00,447,EA,27319.0,USD,4,NaN,NaN,http://lighttree.com/100055011

**Lectura de otro tipo de archivos:**

- ```pd.read_excel(url)```
- ```pd.read_json(url)```
- ```pd.read_xml("archivo.xml")```

**Cargue local de archivos**

**Cargue de un archivo local:**

### 3.3. Explorar Datos
Pandas proporciona funciones útiles para explorar datos:

```head():``` Muestra las primeras filas.

```tail():``` Muestra las últimas filas.

```info():``` Proporciona información sobre el DataFrame.

```describe():``` Muestra estadísticas descriptivas.

```shape:``` Forma del DataFrame (Filas,Columnas)

In [29]:
datos_excel.head()

,orderIdentifier,orderType,vendor.organizationIdentifier,buyer.organizationIdentifier,shipFromInstructionLocation.locationIdentifier,shipToLocation.locationIdentifier,orderStatus,createdDate,requestedShipDate,requestedDeliveryDate,...,quantity,quantityUnits,totalValue,orderValueCurrency,lineCount,totalShippedQuantity,exclude,sourceLink,precio_unitario,precio_unitario_iva
0,100044349,OUTBOUND,LightTree,AHTD,LT-1,AHTD - Bentonville,NaN,2021-06-08T00:00:00,2021-07-20T00:00:00,2021-07-30T00:00:00,...,189,EA,236250,USD,3,NaN,NaN,http://lighttree.com/100044349,1250.000000,1487.500000
1,100044350,OUTBOUND,LightTree,AHTD,LT-1,AHTD - Bentonville,NaN,2021-06-08T00:00:00,2021-07-23T00:00:00,2021-07-30T00:00:00,...,20,EA,25000,USD,3,NaN,NaN,http://lighttree.com/100044350,1250.000000,1487.500000
2,100044353,OUTBOUND,LightTree,AHTD,LT-1,AHTD - Bentonville,NaN,2021-06-08T00:00:00,2021-07-13T00:00:00,2021-07-30T00:00:00,...,212,EA,265000,USD,3,NaN,NaN,http://lighttree.com/100044353,1250.000000,1487.500000
3,100055001,OUTBOUND,LightTree,AHTD,LT-2,AHTD - Bentonville,NaN,2017-07-11T00:00:00,2021-08-10T00:00:00,2021-08-18T00:00:00,...,761,EA,59473,USD,3,NaN,NaN,http://lighttree.com/100055001,78.151117,92.999829
4,100055003,OUTBOUND,LightTree,AHTD,LT-2,AHTD - Bentonville,NaN,2017-07-20T00:00:00,2021-08-11T00:00:00,2021-08-14T00:00:00,...,520,EA,47438,USD,3,NaN,NaN,http://lighttree.com/100055003,91.226923,108.560038

In [30]:
datos_excel.tail()

,orderIdentifier,orderType,vendor.organizationIdentifier,buyer.organizationIdentifier,shipFromInstructionLocation.locationIdentifier,shipToLocation.locationIdentifier,orderStatus,createdDate,requestedShipDate,requestedDeliveryDate,...,quantity,quantityUnits,totalValue,orderValueCurrency,lineCount,totalShippedQuantity,exclude,sourceLink,precio_unitario,precio_unitario_iva
209,100044330,OUTBOUND,LightTree,QPWD,LT-2,QPWD - Ville de Québec,NaN,2021-07-07T00:00:00,2021-08-06T00:00:00,2021-08-12T00:00:00,...,12,EA,15000,USD,3,NaN,NaN,http://lighttree.com/100044330,1250.000000,1487.500000
210,100044331,OUTBOUND,LightTree,QPWD,LT-2,QPWD - Ville de Québec,NaN,2021-07-07T00:00:00,2021-08-04T00:00:00,2021-08-12T00:00:00,...,960,EA,1200000,USD,3,NaN,NaN,http://lighttree.com/100044331,1250.000000,1487.500000
211,100044332,OUTBOUND,LightTree,QPWD,LT-2,QPWD - Ville de Québec,NaN,2021-07-07T00:00:00,2021-08-21T00:00:00,2021-08-27T00:00:00,...,56,EA,70000,USD,3,NaN,NaN,http://lighttree.com/100044332,1250.000000,1487.500000
212,100055004,OUTBOUND,LightTree,QPWD,LT-2,QPWD - Ville de Québec,NaN,2017-07-11T00:00:00,2021-08-10T00:00:00,2021-08-18T00:00:00,...,597,EA,44953,USD,3,NaN,NaN,http://lighttree.com/100055004,75.298157,89.604807
213,100055011,OUTBOUND,LightTree,QPWD,LT-2,QPWD - Ville de Québec,NaN,2017-07-11T00:00:00,2021-08-10T00:00:00,2021-08-18T00:00:00,...,447,EA,27319,USD,4,NaN,NaN,http://lighttree.com/100055011,61.116331,72.728434

In [31]:
datos_excel.info()

<class 'pandas.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 22 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   orderIdentifier                                 214 non-null    int64
 1   orderType                                       214 non-null    str
 2   vendor.organizationIdentifier                   214 non-null    str
 3   buyer.organizationIdentifier                    214 non-null    str
 4   shipFromInstructionLocation.locationIdentifier  214 non-null    str
 5   shipToLocation.locationIdentifier               214 non-null    str
 6   orderStatus                                     0 non-null      float64
 7   createdDate                                     214 non-null    str
 8   requestedShipDate                               214 non-null    str
 9   requestedDeliveryDate                           214 non-null    str
 10  plannedShipDate                                 210 non-null    str
 11  plannedDeliveryDate                             193 non-null    str
 12  quantity                                        214 non-null    int64
 13  quantityUnits                                   214 non-null    str
 14  totalValue                                      214 non-null    int64
 15  orderValueCurrency                              214 non-null    str
 16  lineCount                                       214 non-null    int64
 17  totalShippedQuantity                            0 non-null      float64
 18  exclude                                         0 non-null      float64
 19  sourceLink                                      214 non-null    str
 20  precio_unitario                                 214 non-null    float64
 21  precio_unitario_iva                             214 non-null    float64
dtypes: float64(5), int64(4), str(13)
memory usage: 73.3 KB

In [32]:
datos_excel.describe()

,orderIdentifier,orderStatus,quantity,totalValue,lineCount,totalShippedQuantity,exclude,precio_unitario,precio_unitario_iva
count,2.140000e+02,0.0,214.000000,2.140000e+02,214.000000,0.0,0.0,214.000000,214.000000
mean,8.069695e+08,NaN,278.098131,1.229496e+05,1.607477,NaN,NaN,582.197756,692.815330
std,3.707773e+08,NaN,325.289506,2.411097e+05,1.023269,NaN,NaN,837.740331,996.910994
min,1.000443e+08,NaN,4.000000,1.320000e+02,1.000000,NaN,NaN,3.000000,3.570000
25%,1.000066e+09,NaN,74.250000,7.044000e+03,1.000000,NaN,NaN,55.000000,65.450000
50%,1.000567e+09,NaN,124.000000,3.904000e+04,1.000000,NaN,NaN,203.000000,241.570000
75%,1.000567e+09,NaN,320.000000,1.210240e+05,3.000000,NaN,NaN,1232.500000,1466.675000
max,1.000568e+09,NaN,1400.000000,1.769600e+06,4.000000,NaN,NaN,5530.000000,6580.700000

In [39]:
datos_excel.shape

(214, 22)

### 3.4. Filtrar Datos

**Filtrado básico:**

In [46]:
datos_excel[(datos_excel['vendor.organizationIdentifier'] == 'SilverOptics')]

,orderIdentifier,orderType,vendor.organizationIdentifier,buyer.organizationIdentifier,shipFromInstructionLocation.locationIdentifier,shipToLocation.locationIdentifier,orderStatus,createdDate,requestedShipDate,requestedDeliveryDate,...,quantity,quantityUnits,totalValue,orderValueCurrency,lineCount,totalShippedQuantity,exclude,sourceLink,precio_unitario,precio_unitario_iva
42,1000567251,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-1,NaN,2021-07-15T00:00:00,2021-07-22T00:00:00,2021-07-26T00:00:00,...,44,EA,4752,USD,1,NaN,NaN,http://lighttree.com/1000567251,108.0,128.52
61,1000567332,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-1,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,124,EA,13392,USD,1,NaN,NaN,http://lighttree.com/1000567332,108.0,128.52
64,1000567338,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-1,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,512,EA,48640,USD,1,NaN,NaN,http://lighttree.com/1000567338,95.0,113.05
75,1000567370,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-1,NaN,2021-07-08T00:00:00,2021-07-15T00:00:00,2021-07-19T00:00:00,...,56,EA,5320,USD,1,NaN,NaN,http://lighttree.com/1000567370,95.0,113.05
102,1000567463,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-1,NaN,2021-06-29T00:00:00,2021-07-06T00:00:00,2021-07-10T00:00:00,...,75,EA,8100,USD,1,NaN,NaN,http://lighttree.com/1000567463,108.0,128.52
135,1000567230,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,124,EA,13392,USD,1,NaN,NaN,http://lighttree.com/1000567230,108.0,128.52
157,1000567315,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,320,EA,34560,USD,1,NaN,NaN,http://lighttree.com/1000567315,108.0,128.52
180,1000567425,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,320,EA,34560,USD,1,NaN,NaN,http://lighttree.com/1000567425,108.0,128.52

**Filtrado multiplies condiciones:**

In [ ]:
## Conjuncion con el simbolo &
datos_excel[(datos_excel['vendor.organizationIdentifier'] == 'SilverOptics') & (datos_excel['quantity'] > 200)]

In [48]:
## Disyuncion con el simbolo |
datos_excel[(datos_excel['vendor.organizationIdentifier'] == 'SilverOptics') | (datos_excel['quantity'] > 200)]

,orderIdentifier,orderType,vendor.organizationIdentifier,buyer.organizationIdentifier,shipFromInstructionLocation.locationIdentifier,shipToLocation.locationIdentifier,orderStatus,createdDate,requestedShipDate,requestedDeliveryDate,...,quantity,quantityUnits,totalValue,orderValueCurrency,lineCount,totalShippedQuantity,exclude,sourceLink,precio_unitario,precio_unitario_iva
2,100044353,OUTBOUND,LightTree,AHTD,LT-1,AHTD - Bentonville,NaN,2021-06-08T00:00:00,2021-07-13T00:00:00,2021-07-30T00:00:00,...,212,EA,265000,USD,3,NaN,NaN,http://lighttree.com/100044353,1250.000000,1487.500000
3,100055001,OUTBOUND,LightTree,AHTD,LT-2,AHTD - Bentonville,NaN,2017-07-11T00:00:00,2021-08-10T00:00:00,2021-08-18T00:00:00,...,761,EA,59473,USD,3,NaN,NaN,http://lighttree.com/100055001,78.151117,92.999829
4,100055003,OUTBOUND,LightTree,AHTD,LT-2,AHTD - Bentonville,NaN,2017-07-20T00:00:00,2021-08-11T00:00:00,2021-08-14T00:00:00,...,520,EA,47438,USD,3,NaN,NaN,http://lighttree.com/100055003,91.226923,108.560038
7,100044354,OUTBOUND,LightTree,AHTD,LT-1,AHTD - Bentonville,NaN,2021-06-08T00:00:00,2021-06-30T00:00:00,2021-07-07T00:00:00,...,208,EA,260000,USD,3,NaN,NaN,http://lighttree.com/100044354,1250.000000,1487.500000
8,100044355,OUTBOUND,LightTree,AHTD,LT-1,AHTD - Bentonville,NaN,2021-06-08T00:00:00,2021-06-30T00:00:00,2021-07-07T00:00:00,...,400,EA,500000,USD,3,NaN,NaN,http://lighttree.com/100044355,1250.000000,1487.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,100044342,OUTBOUND,LightTree,NYDOT,LT-1,NYDOT - New Rochelle,NaN,2021-06-15T00:00:00,2021-07-07T00:00:00,2021-07-11T00:00:00,...,320,EA,400000,USD,3,NaN,NaN,http://lighttree.com/100044342,1250.000000,1487.500000
208,100044329,OUTBOUND,LightTree,QPWD,LT-2,QPWD - Ville de Québec,NaN,2021-07-07T00:00:00,2021-07-29T00:00:00,2021-08-04T00:00:00,...,320,EA,400000,USD,3,NaN,NaN,http://lighttree.com/100044329,1250.000000,1487.500000
210,100044331,OUTBOUND,LightTree,QPWD,LT-2,QPWD - Ville de Québec,NaN,2021-07-07T00:00:00,2021-08-04T00:00:00,2021-08-12T00:00:00,...,960,EA,1200000,USD,3,NaN,NaN,http://lighttree.com/100044331,1250.000000,1487.500000
212,100055004,OUTBOUND,LightTree,QPWD,LT-2,QPWD - Ville de Québec,NaN,2017-07-11T00:00:00,2021-08-10T00:00:00,2021-08-18T00:00:00,...,597,EA,44953,USD,3,NaN,NaN,http://lighttree.com/100055004,75.298157,89.604807
213,100055011,OUTBOUND,LightTree,QPWD,LT-2,QPWD - Ville de Québec,NaN,2017-07-11T00:00:00,2021-08-10T00:00:00,2021-08-18T00:00:00,...,447,EA,27319,USD,4,NaN,NaN,http://lighttree.com/100055011,61.116331,72.728434

**Filtrado con función where:**

In [53]:
datos_excel.where(datos_excel['vendor.organizationIdentifier'] == 'SilverOptics').dropna(subset=['vendor.organizationIdentifier'])

,orderIdentifier,orderType,vendor.organizationIdentifier,buyer.organizationIdentifier,shipFromInstructionLocation.locationIdentifier,shipToLocation.locationIdentifier,orderStatus,createdDate,requestedShipDate,requestedDeliveryDate,...,quantity,quantityUnits,totalValue,orderValueCurrency,lineCount,totalShippedQuantity,exclude,sourceLink,precio_unitario,precio_unitario_iva
42,1.000567e+09,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-1,NaN,2021-07-15T00:00:00,2021-07-22T00:00:00,2021-07-26T00:00:00,...,44.0,EA,4752.0,USD,1.0,NaN,NaN,http://lighttree.com/1000567251,108.0,128.52
61,1.000567e+09,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-1,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,124.0,EA,13392.0,USD,1.0,NaN,NaN,http://lighttree.com/1000567332,108.0,128.52
64,1.000567e+09,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-1,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,512.0,EA,48640.0,USD,1.0,NaN,NaN,http://lighttree.com/1000567338,95.0,113.05
75,1.000567e+09,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-1,NaN,2021-07-08T00:00:00,2021-07-15T00:00:00,2021-07-19T00:00:00,...,56.0,EA,5320.0,USD,1.0,NaN,NaN,http://lighttree.com/1000567370,95.0,113.05
102,1.000567e+09,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-1,NaN,2021-06-29T00:00:00,2021-07-06T00:00:00,2021-07-10T00:00:00,...,75.0,EA,8100.0,USD,1.0,NaN,NaN,http://lighttree.com/1000567463,108.0,128.52
135,1.000567e+09,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,124.0,EA,13392.0,USD,1.0,NaN,NaN,http://lighttree.com/1000567230,108.0,128.52
157,1.000567e+09,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,320.0,EA,34560.0,USD,1.0,NaN,NaN,http://lighttree.com/1000567315,108.0,128.52
180,1.000567e+09,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,320.0,EA,34560.0,USD,1.0,NaN,NaN,http://lighttree.com/1000567425,108.0,128.52

**Filtrado loc e iloc:**

- ```loc:``` Se utiliza para seleccionar filas y columnas por etiquetas (nombres de filas y columnas).

- ```iloc:``` Se utiliza para seleccionar filas y columnas por índices numéricos (posición).

___loc___

___iloc___

### 3.5. Agregar columnas

,orderIdentifier,orderType,vendor.organizationIdentifier,buyer.organizationIdentifier,shipFromInstructionLocation.locationIdentifier,shipToLocation.locationIdentifier,orderStatus,createdDate,requestedShipDate,requestedDeliveryDate,plannedShipDate,plannedDeliveryDate,quantity,quantityUnits,totalValue,orderValueCurrency,lineCount,totalShippedQuantity,exclude,sourceLink
0,100044349,OUTBOUND,LightTree,AHTD,LT-1,AHTD - Bentonville,NaN,2021-06-08T00:00:00,2021-07-20T00:00:00,2021-07-30T00:00:00,2021-07-23T00:00:00,2021-07-30T00:00:00,189,EA,236250.00,USD,3,NaN,NaN,http://lighttree.com/100044349
1,100044350,OUTBOUND,LightTree,AHTD,LT-1,AHTD - Bentonville,NaN,2021-06-08T00:00:00,2021-07-23T00:00:00,2021-07-30T00:00:00,2021-07-23T00:00:00,2021-07-30T00:00:00,20,EA,25000.00,USD,3,NaN,NaN,http://lighttree.com/100044350
2,100044353,OUTBOUND,LightTree,AHTD,LT-1,AHTD - Bentonville,NaN,2021-06-08T00:00:00,2021-07-13T00:00:00,2021-07-30T00:00:00,2021-07-23T00:00:00,2021-07-30T00:00:00,212,EA,265000.00,USD,3,NaN,NaN,http://lighttree.com/100044353
3,100055001,OUTBOUND,LightTree,AHTD,LT-2,AHTD - Bentonville,NaN,2017-07-11T00:00:00,2021-08-10T00:00:00,2021-08-18T00:00:00,2021-08-10T00:00:00,2021-08-18T00:00:00,761,EA,59473.00,USD,3,NaN,NaN,http://lighttree.com/100055001
4,100055003,OUTBOUND,LightTree,AHTD,LT-2,AHTD - Bentonville,NaN,2017-07-20T00:00:00,2021-08-11T00:00:00,2021-08-14T00:00:00,2021-08-11T00:00:00,2021-08-14T00:00:00,520,EA,47438.00,USD,3,NaN,NaN,http://lighttree.com/100055003

### 3.6. Eliminar columnas

### 3.7. Quitar duplicados

### 3.8. Agrupar datos

### 3.9. Merge

![Diagrama de JOINs en SQL](https://www.hostingplus.com.co/wp-content/uploads/2021/06/JOIN.jpg)

### 4. Exportar

### Otras funcionalidades

| **Tema**                        | **Descripción**                                                                 | **Funciones/Métodos Clave**                     | **Ejemplo y Resultado**                                                                 |
|----------------------------------|---------------------------------------------------------------------------------|-------------------------------------------------|-----------------------------------------------------------------------------------------|
| **Manejo de Datos Faltantes**    | Identificar, eliminar o rellenar datos faltantes.                               | `isna()`, `dropna()`, `fillna()`, `interpolate()`| ```df["columna"].fillna(df["columna"].mean(), inplace=True)```<br>**Resultado:** Rellena los valores faltantes con la media. |
| **Aplicar Funciones**            | Aplicar funciones personalizadas a columnas o filas.                            | `apply()`, `map()`, `applymap()`                | ```df["columna"] = df["columna"].apply(lambda x: x * 2)```<br>**Resultado:** Multiplica cada valor por 2. |
| **Ordenar Datos**                | Ordenar DataFrames por columnas o índices.                                      | `sort_values()`, `sort_index()`                 | ```df.sort_values("Value", ascending=False)```<br>**Resultado:** Ordena por "Value" de forma descendente. |
| **Pivot Tables**                 | Crear tablas dinámicas para resumir datos.                                      | `pivot_table()`                                | ```df.pivot_table(values="Value", index="Country Name", columns="Year", aggfunc="sum")```<br>**Resultado:** Tabla dinámica con la suma de "Value" por país y año. |
| **Melt y Pivot**                 | Transformar DataFrames entre formatos largo y ancho.                            | `melt()`, `pivot()`                            | ```df.melt(id_vars=["Country Name", "Year"], value_vars=["Value", "Value_2"])```<br>**Resultado:** Convierte el DataFrame a formato largo. |
| **Concatenación de DataFrames**  | Combinar DataFrames vertical u horizontalmente.                                 | `concat()`                                     | ```pd.concat([df1, df2], axis=0)```<br>**Resultado:** Combina dos DataFrames verticalmente. |
| **Manejo de Datos de Texto**     | Manipular columnas de texto (extraer, dividir, reemplazar).                     | `str.upper()`, `str.split()`, `str.replace()`  | ```df["columna"] = df["columna"].str.upper()```<br>**Resultado:** Convierte el texto a mayúsculas. |
| **Manejo de Fechas y Tiempos**   | Trabajar con columnas de fechas y realizar operaciones temporales.              | `pd.to_datetime()`, `dt.year`, `dt.month`      | ```df["fecha"] = pd.to_datetime(df["fecha"])```<br>**Resultado:** Convierte la columna a tipo `datetime`. |
| **Manejo de Datos Categóricos**  | Convertir columnas a tipo categórico y crear variables dummy.                   | `astype("category")`, `pd.get_dummies()`       | ```df["columna"] = df["columna"].astype("category")```<br>**Resultado:** Convierte la columna a tipo categórico. |
| **Manejo de Grandes Volúmenes**  | Leer y procesar archivos grandes en bloques.                                    | `chunksize` en `read_csv()`                    | ```for chunk in pd.read_csv("archivo.csv", chunksize=1000): procesar(chunk)```<br>**Resultado:** Lee el archivo en bloques de 1000 filas. |
| **Exportación de Datos**         | Guardar DataFrames en diferentes formatos (CSV, Excel, JSON, etc.).             | `to_csv()`, `to_excel()`, `to_json()`          | ```df.to_csv("datos.csv", index=False)```<br>**Resultado:** Guarda el DataFrame en un archivo CSV. |
| **Visualización de Datos**       | Crear gráficos directamente desde pandas.                                       | `plot()`, `hist()`, `boxplot()`                | ```df.plot(x="Year", y="Value", kind="line")```<br>**Resultado:** Genera un gráfico de líneas. |
| **Optimización de Código**       | Evitar bucles y usar operaciones vectorizadas.                                  | `eval()`, `query()`                            | ```df.query("Value > 1000000")```<br>**Resultado:** Filtra filas donde "Value" es mayor a 1,000,000. |
| **Trabajo con Multi-Index**      | Crear y manipular DataFrames con múltiples niveles de índice.                   | `set_index()`, `stack()`, `unstack()`          | ```df.set_index(["Country Name", "Year"])```<br>**Resultado:** Crea un DataFrame con Multi-Index. |
| **Casos Prácticos y Proyectos**  | Ejercicios y proyectos para aplicar lo aprendido en datasets reales.            | -                                              | **Ejemplo:** Análisis de ventas mensuales.<br>**Resultado:** Informe con insights clave. |