# Introducción a Pandas: Principales Funciones y Usos

En este Notebook, exploraremos **pandas**, una de las librerías más populares de Python para la manipulación y análisis de datos. Aprenderemos sus principales funciones y cómo usarlas en proyectos reales.

---

## 1. ¿Qué es Pandas?

**Pandas** es una librería de Python diseñada para trabajar con datos tabulares, como hojas de cálculo o bases de datos. Es especialmente útil para:
- Leer y escribir datos en diferentes formatos (CSV, Excel, JSON, etc.).
- Limpiar y transformar datos.
- Realizar análisis estadísticos.
- Visualizar datos (en combinación con otras librerías como Matplotlib o Seaborn).

### Instalación de Pandas
Si no tienes pandas instalado, puedes instalarlo con:
```bash
pip install pandas

In [24]:
!pip install pandas
!pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: pandas in C:\Users\Usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages (3.0.0)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\Usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: openpyxl in C:\Users\Usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\Usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages (from openpyxl) (2.0.0)

# 2. Principales Estructuras de Datos en Pandas
Pandas tiene dos estructuras principales:

**1. Series:** es una estructura unidimensional, similar a una lista o columna en una tabla.

**2. DataFrame:** es una estructura bidimensional, similar a una tabla con filas y columnas.

# 3. Principales Funciones y Usos de Pandas

### 3.1. Crear un DataFrame

Un DataFrame es la estructura principal de pandas. Podemos crearlo a partir de un diccionario, una lista o leyendo un archivo.

In [25]:
import pandas as pd

datos = pd.DataFrame(
    data={
        "Nombre": ["Juan", "María", "Pedro", "Ana"],
        "Edad": [28, 34, 22, 30],
        "Ciudad": ["Madrid", "Barcelona", "Valencia", "Sevilla"],
    }
)
datos

  Nombre  Edad     Ciudad
0   Juan    28     Madrid
1  María    34  Barcelona
2  Pedro    22   Valencia
3    Ana    30    Sevilla

In [26]:
datos_excel = pd.read_excel("archivo_excel.xlsx")
datos_excel

,orderIdentifier,orderType,vendor.organizationIdentifier,buyer.organizationIdentifier,shipFromInstructionLocation.locationIdentifier,shipToLocation.locationIdentifier,orderStatus,createdDate,requestedShipDate,requestedDeliveryDate,...,quantity,quantityUnits,totalValue,orderValueCurrency,lineCount,totalShippedQuantity,exclude,sourceLink,precio_unitario,precio_unitario_iva
0,1000567495,INBOUND,F & M,LightTree,F & M - Columbus,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,124,EA,6200,USD,1,NaN,NaN,http://lighttree.com/1000567495,50.0,59.50
1,1000567490,INBOUND,Luminar,LightTree,Luminar - Palm Beach Gardens,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,124,EA,117800,USD,1,NaN,NaN,http://lighttree.com/1000567490,950.0,1130.50
2,1000567484,INBOUND,Flexilux,LightTree,Flexilux - Worcester,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,124,EA,569408,USD,1,NaN,NaN,http://lighttree.com/1000567484,4592.0,5464.48
3,1000567483,INBOUND,Brewers,LightTree,Brewers - Phoenix,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,124,EA,159588,USD,1,NaN,NaN,http://lighttree.com/1000567483,1287.0,1531.53
4,1000567481,INBOUND,McGrey,LightTree,McGrey - Mt Sterling,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,320,EA,316800,USD,1,NaN,NaN,http://lighttree.com/1000567481,990.0,1178.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,1000567351,INBOUND,Total Source,LightTree,Total Source - Waukesha,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,124,EA,121024,USD,1,NaN,NaN,http://lighttree.com/1000567351,976.0,1161.44
164,1000567364,INBOUND,Mueller,LightTree,Mueller - Pittsburgh,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,320,EA,135040,USD,1,NaN,NaN,http://lighttree.com/1000567364,422.0,502.18
165,1000567374,INBOUND,EM,LightTree,EM - Hemphill,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,320,EA,6080,USD,1,NaN,NaN,http://lighttree.com/1000567374,19.0,22.61
166,1000567376,INBOUND,Ripley,LightTree,Ripley - Trenton,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,320,EA,112000,USD,1,NaN,NaN,http://lighttree.com/1000567376,350.0,416.50
167,1000567378,INBOUND,Interalloy,LightTree,Interalloy - Bozeman,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,124,EA,620,USD,1,NaN,NaN,http://lighttree.com/1000567378,5.0,5.95

### 3.2. Leer un Archivo CSV
Pandas puede leer archivos CSV directamente desde una URL o un archivo local.

In [27]:
datos_csv = pd.read_csv("Order_v3.csv", encoding="latin-1")
datos_csv

,orderIdentifier,orderType,vendor.organizationIdentifier,buyer.organizationIdentifier,shipFromInstructionLocation.locationIdentifier,shipToLocation.locationIdentifier,orderStatus,createdDate,requestedShipDate,requestedDeliveryDate,plannedShipDate,plannedDeliveryDate,quantity,quantityUnits,totalValue,orderValueCurrency,lineCount,totalShippedQuantity,exclude,sourceLink
0,100044349,OUTBOUND,LightTree,AHTD,LT-1,AHTD - Bentonville,NaN,2021-06-08T00:00:00,2021-07-20T00:00:00,2021-07-30T00:00:00,2021-07-23T00:00:00,2021-07-30T00:00:00,189,EA,236250.0,USD,3,NaN,NaN,http://lighttree.com/100044349
1,100044350,OUTBOUND,LightTree,AHTD,LT-1,AHTD - Bentonville,NaN,2021-06-08T00:00:00,2021-07-23T00:00:00,2021-07-30T00:00:00,2021-07-23T00:00:00,2021-07-30T00:00:00,20,EA,25000.0,USD,3,NaN,NaN,http://lighttree.com/100044350
2,100044353,OUTBOUND,LightTree,AHTD,LT-1,AHTD - Bentonville,NaN,2021-06-08T00:00:00,2021-07-13T00:00:00,2021-07-30T00:00:00,2021-07-23T00:00:00,2021-07-30T00:00:00,212,EA,265000.0,USD,3,NaN,NaN,http://lighttree.com/100044353
3,100055001,OUTBOUND,LightTree,AHTD,LT-2,AHTD - Bentonville,NaN,2017-07-11T00:00:00,2021-08-10T00:00:00,2021-08-18T00:00:00,2021-08-10T00:00:00,2021-08-18T00:00:00,761,EA,59473.0,USD,3,NaN,NaN,http://lighttree.com/100055001
4,100055003,OUTBOUND,LightTree,AHTD,LT-2,AHTD - Bentonville,NaN,2017-07-20T00:00:00,2021-08-11T00:00:00,2021-08-14T00:00:00,2021-08-11T00:00:00,2021-08-14T00:00:00,520,EA,47438.0,USD,3,NaN,NaN,http://lighttree.com/100055003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,100044330,OUTBOUND,LightTree,QPWD,LT-2,QPWD - Ville de Québec,NaN,2021-07-07T00:00:00,2021-08-06T00:00:00,2021-08-12T00:00:00,2021-08-06T00:00:00,2021-08-12T00:00:00,12,EA,15000.0,USD,3,NaN,NaN,http://lighttree.com/100044330
210,100044331,OUTBOUND,LightTree,QPWD,LT-2,QPWD - Ville de Québec,NaN,2021-07-07T00:00:00,2021-08-04T00:00:00,2021-08-12T00:00:00,2021-08-06T00:00:00,2021-08-12T00:00:00,960,EA,1200000.0,USD,3,NaN,NaN,http://lighttree.com/100044331
211,100044332,OUTBOUND,LightTree,QPWD,LT-2,QPWD - Ville de Québec,NaN,2021-07-07T00:00:00,2021-08-21T00:00:00,2021-08-27T00:00:00,2021-08-21T00:00:00,2021-08-27T00:00:00,56,EA,70000.0,USD,3,NaN,NaN,http://lighttree.com/100044332
212,100055004,OUTBOUND,LightTree,QPWD,LT-2,QPWD - Ville de Québec,NaN,2017-07-11T00:00:00,2021-08-10T00:00:00,2021-08-18T00:00:00,NaN,NaN,597,EA,44953.0,USD,3,NaN,NaN,http://lighttree.com/100055004
213,100055011,OUTBOUND,LightTree,QPWD,LT-2,QPWD - Ville de Québec,NaN,2017-07-11T00:00:00,2021-08-10T00:00:00,2021-08-18T00:00:00,2021-08-10T00:00:00,2021-08-18T00:00:00,447,EA,27319.0,USD,4,NaN,NaN,http://lighttree.com/100055011

**Lectura de otro tipo de archivos:**

- ```pd.read_excel(url)```
- ```pd.read_json(url)```
- ```pd.read_xml("archivo.xml")```

**Cargue local de archivos**

**Cargue de un archivo local:**

### 3.3. Explorar Datos
Pandas proporciona funciones útiles para explorar datos:

```head():``` Muestra las primeras filas.

```tail():``` Muestra las últimas filas.

```info():``` Proporciona información sobre el DataFrame.

```describe():``` Muestra estadísticas descriptivas.

```shape:``` Forma del DataFrame (Filas,Columnas)

In [28]:
datos_excel.head()

,orderIdentifier,orderType,vendor.organizationIdentifier,buyer.organizationIdentifier,shipFromInstructionLocation.locationIdentifier,shipToLocation.locationIdentifier,orderStatus,createdDate,requestedShipDate,requestedDeliveryDate,...,quantity,quantityUnits,totalValue,orderValueCurrency,lineCount,totalShippedQuantity,exclude,sourceLink,precio_unitario,precio_unitario_iva
0,1000567495,INBOUND,F & M,LightTree,F & M - Columbus,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,124,EA,6200,USD,1,NaN,NaN,http://lighttree.com/1000567495,50.0,59.50
1,1000567490,INBOUND,Luminar,LightTree,Luminar - Palm Beach Gardens,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,124,EA,117800,USD,1,NaN,NaN,http://lighttree.com/1000567490,950.0,1130.50
2,1000567484,INBOUND,Flexilux,LightTree,Flexilux - Worcester,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,124,EA,569408,USD,1,NaN,NaN,http://lighttree.com/1000567484,4592.0,5464.48
3,1000567483,INBOUND,Brewers,LightTree,Brewers - Phoenix,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,124,EA,159588,USD,1,NaN,NaN,http://lighttree.com/1000567483,1287.0,1531.53
4,1000567481,INBOUND,McGrey,LightTree,McGrey - Mt Sterling,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,320,EA,316800,USD,1,NaN,NaN,http://lighttree.com/1000567481,990.0,1178.10

In [29]:
datos_excel.tail()

,orderIdentifier,orderType,vendor.organizationIdentifier,buyer.organizationIdentifier,shipFromInstructionLocation.locationIdentifier,shipToLocation.locationIdentifier,orderStatus,createdDate,requestedShipDate,requestedDeliveryDate,...,quantity,quantityUnits,totalValue,orderValueCurrency,lineCount,totalShippedQuantity,exclude,sourceLink,precio_unitario,precio_unitario_iva
163,1000567351,INBOUND,Total Source,LightTree,Total Source - Waukesha,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,124,EA,121024,USD,1,NaN,NaN,http://lighttree.com/1000567351,976.0,1161.44
164,1000567364,INBOUND,Mueller,LightTree,Mueller - Pittsburgh,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,320,EA,135040,USD,1,NaN,NaN,http://lighttree.com/1000567364,422.0,502.18
165,1000567374,INBOUND,EM,LightTree,EM - Hemphill,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,320,EA,6080,USD,1,NaN,NaN,http://lighttree.com/1000567374,19.0,22.61
166,1000567376,INBOUND,Ripley,LightTree,Ripley - Trenton,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,320,EA,112000,USD,1,NaN,NaN,http://lighttree.com/1000567376,350.0,416.50
167,1000567378,INBOUND,Interalloy,LightTree,Interalloy - Bozeman,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,124,EA,620,USD,1,NaN,NaN,http://lighttree.com/1000567378,5.0,5.95

In [30]:
datos_excel.info()

<class 'pandas.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 22 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   orderIdentifier                                 168 non-null    int64
 1   orderType                                       168 non-null    str
 2   vendor.organizationIdentifier                   168 non-null    str
 3   buyer.organizationIdentifier                    168 non-null    str
 4   shipFromInstructionLocation.locationIdentifier  168 non-null    str
 5   shipToLocation.locationIdentifier               168 non-null    str
 6   orderStatus                                     0 non-null      float64
 7   createdDate                                     168 non-null    str
 8   requestedShipDate                               168 non-null    str
 9   requestedDeliveryDate                           168 non-null    str
 10  plannedShipDate                                 166 non-null    str
 11  plannedDeliveryDate                             149 non-null    str
 12  quantity                                        168 non-null    int64
 13  quantityUnits                                   168 non-null    str
 14  totalValue                                      168 non-null    int64
 15  orderValueCurrency                              168 non-null    str
 16  lineCount                                       168 non-null    int64
 17  totalShippedQuantity                            0 non-null      float64
 18  exclude                                         0 non-null      float64
 19  sourceLink                                      168 non-null    str
 20  precio_unitario                                 168 non-null    float64
 21  precio_unitario_iva                             168 non-null    float64
dtypes: float64(5), int64(4), str(13)
memory usage: 57.6 KB

In [31]:
datos_excel.describe()

,orderIdentifier,orderStatus,quantity,totalValue,lineCount,totalShippedQuantity,exclude,precio_unitario,precio_unitario_iva
count,1.680000e+02,0.0,168.000000,1.680000e+02,168.000000,0.0,0.0,168.000000,168.000000
mean,1.000532e+09,NaN,283.410714,1.061578e+05,1.214286,NaN,NaN,482.946429,574.706250
std,1.295037e+05,NaN,345.379984,2.384429e+05,0.774928,NaN,NaN,881.056725,1048.457502
min,1.000066e+09,NaN,44.000000,1.320000e+02,1.000000,NaN,NaN,3.000000,3.570000
25%,1.000567e+09,NaN,75.000000,5.356000e+03,1.000000,NaN,NaN,50.000000,59.500000
50%,1.000567e+09,NaN,124.000000,2.720500e+04,1.000000,NaN,NaN,142.000000,168.980000
75%,1.000567e+09,NaN,320.000000,1.104250e+05,1.000000,NaN,NaN,455.000000,541.450000
max,1.000568e+09,NaN,1400.000000,1.769600e+06,4.000000,NaN,NaN,5530.000000,6580.700000

In [32]:
datos_excel.shape

(168, 22)

### 3.4. Filtrar Datos

**Filtrar por columnas**

In [33]:
## Filtro una sola columna de información - Esto genera una serie de pandas
datos_excel['buyer.organizationIdentifier']

0      LightTree
1      LightTree
2      LightTree
3      LightTree
4      LightTree
         ...
163    LightTree
164    LightTree
165    LightTree
166    LightTree
167    LightTree
Name: buyer.organizationIdentifier, Length: 168, dtype: str

In [34]:
## Filtro 2 o mas columnas de informacion - Esto genera un DataFrame de pandas
datos_excel[['vendor.organizationIdentifier','orderType', 'quantity']]

    vendor.organizationIdentifier orderType  quantity
0                           F & M   INBOUND       124
1                         Luminar   INBOUND       124
2                        Flexilux   INBOUND       124
3                         Brewers   INBOUND       124
4                          McGrey   INBOUND       320
..                            ...       ...       ...
163                  Total Source   INBOUND       124
164                       Mueller   INBOUND       320
165                            EM   INBOUND       320
166                        Ripley   INBOUND       320
167                    Interalloy   INBOUND       124

[168 rows x 3 columns]

**Filtrado básico:**

In [35]:
datos_excel[(datos_excel['vendor.organizationIdentifier'] == 'SilverOptics')]

,orderIdentifier,orderType,vendor.organizationIdentifier,buyer.organizationIdentifier,shipFromInstructionLocation.locationIdentifier,shipToLocation.locationIdentifier,orderStatus,createdDate,requestedShipDate,requestedDeliveryDate,...,quantity,quantityUnits,totalValue,orderValueCurrency,lineCount,totalShippedQuantity,exclude,sourceLink,precio_unitario,precio_unitario_iva
19,1000567425,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,320,EA,34560,USD,1,NaN,NaN,http://lighttree.com/1000567425,108.0,128.52
42,1000567251,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-1,NaN,2021-07-15T00:00:00,2021-07-22T00:00:00,2021-07-26T00:00:00,...,44,EA,4752,USD,1,NaN,NaN,http://lighttree.com/1000567251,108.0,128.52
61,1000567332,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-1,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,124,EA,13392,USD,1,NaN,NaN,http://lighttree.com/1000567332,108.0,128.52
64,1000567338,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-1,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,512,EA,48640,USD,1,NaN,NaN,http://lighttree.com/1000567338,95.0,113.05
75,1000567370,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-1,NaN,2021-07-08T00:00:00,2021-07-15T00:00:00,2021-07-19T00:00:00,...,56,EA,5320,USD,1,NaN,NaN,http://lighttree.com/1000567370,95.0,113.05
102,1000567463,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-1,NaN,2021-06-29T00:00:00,2021-07-06T00:00:00,2021-07-10T00:00:00,...,75,EA,8100,USD,1,NaN,NaN,http://lighttree.com/1000567463,108.0,128.52
135,1000567230,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,124,EA,13392,USD,1,NaN,NaN,http://lighttree.com/1000567230,108.0,128.52
157,1000567315,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,320,EA,34560,USD,1,NaN,NaN,http://lighttree.com/1000567315,108.0,128.52

**Filtrado multiplies condiciones:**

In [36]:
## Conjuncion con el simbolo &
datos_excel[(datos_excel['vendor.organizationIdentifier'] == 'SilverOptics') & (datos_excel['quantity'] > 200)]

,orderIdentifier,orderType,vendor.organizationIdentifier,buyer.organizationIdentifier,shipFromInstructionLocation.locationIdentifier,shipToLocation.locationIdentifier,orderStatus,createdDate,requestedShipDate,requestedDeliveryDate,...,quantity,quantityUnits,totalValue,orderValueCurrency,lineCount,totalShippedQuantity,exclude,sourceLink,precio_unitario,precio_unitario_iva
19,1000567425,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,320,EA,34560,USD,1,NaN,NaN,http://lighttree.com/1000567425,108.0,128.52
64,1000567338,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-1,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,512,EA,48640,USD,1,NaN,NaN,http://lighttree.com/1000567338,95.0,113.05
157,1000567315,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,320,EA,34560,USD,1,NaN,NaN,http://lighttree.com/1000567315,108.0,128.52

In [37]:
## Disyuncion con el simbolo |
datos_excel[(datos_excel['vendor.organizationIdentifier'] == 'SilverOptics') | (datos_excel['quantity'] > 200)]

,orderIdentifier,orderType,vendor.organizationIdentifier,buyer.organizationIdentifier,shipFromInstructionLocation.locationIdentifier,shipToLocation.locationIdentifier,orderStatus,createdDate,requestedShipDate,requestedDeliveryDate,...,quantity,quantityUnits,totalValue,orderValueCurrency,lineCount,totalShippedQuantity,exclude,sourceLink,precio_unitario,precio_unitario_iva
4,1000567481,INBOUND,McGrey,LightTree,McGrey - Mt Sterling,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,320,EA,316800,USD,1,NaN,NaN,http://lighttree.com/1000567481,990.0,1178.10
5,1000567478,INBOUND,Total Source,LightTree,Total Source - Waukesha,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,320,EA,312320,USD,1,NaN,NaN,http://lighttree.com/1000567478,976.0,1161.44
6,1000567477,INBOUND,Hardy,LightTree,Hardy - Salina,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,320,EA,7680,USD,1,NaN,NaN,http://lighttree.com/1000567477,24.0,28.56
7,1000567476,INBOUND,EM,LightTree,EM - Hemphill,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,320,EA,6080,USD,1,NaN,NaN,http://lighttree.com/1000567476,19.0,22.61
9,1000567468,INBOUND,Mueller,LightTree,Mueller - Pittsburgh,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,320,EA,131840,USD,1,NaN,NaN,http://lighttree.com/1000567468,412.0,490.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,1000567327,INBOUND,Mueller,LightTree,Mueller - Pittsburgh,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,320,EA,135040,USD,1,NaN,NaN,http://lighttree.com/1000567327,422.0,502.18
162,1000567346,INBOUND,Interalloy,LightTree,Interalloy - Bozeman,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,320,EA,960,USD,1,NaN,NaN,http://lighttree.com/1000567346,3.0,3.57
164,1000567364,INBOUND,Mueller,LightTree,Mueller - Pittsburgh,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,320,EA,135040,USD,1,NaN,NaN,http://lighttree.com/1000567364,422.0,502.18
165,1000567374,INBOUND,EM,LightTree,EM - Hemphill,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,320,EA,6080,USD,1,NaN,NaN,http://lighttree.com/1000567374,19.0,22.61
166,1000567376,INBOUND,Ripley,LightTree,Ripley - Trenton,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,320,EA,112000,USD,1,NaN,NaN,http://lighttree.com/1000567376,350.0,416.50

In [38]:
## Es posible combinar filtros de filas y de columnas para obtener solo la información que nos interesa
datos_excel[['vendor.organizationIdentifier','orderType', 'quantity']][(datos_excel['vendor.organizationIdentifier'] == 'SilverOptics')]

    vendor.organizationIdentifier orderType  quantity
19                   SilverOptics   INBOUND       320
42                   SilverOptics   INBOUND        44
61                   SilverOptics   INBOUND       124
64                   SilverOptics   INBOUND       512
75                   SilverOptics   INBOUND        56
102                  SilverOptics   INBOUND        75
135                  SilverOptics   INBOUND       124
157                  SilverOptics   INBOUND       320

**Filtrado con función where:**

In [39]:
datos_excel.where(datos_excel['vendor.organizationIdentifier'] == 'SilverOptics').dropna(subset=['vendor.organizationIdentifier'])

,orderIdentifier,orderType,vendor.organizationIdentifier,buyer.organizationIdentifier,shipFromInstructionLocation.locationIdentifier,shipToLocation.locationIdentifier,orderStatus,createdDate,requestedShipDate,requestedDeliveryDate,...,quantity,quantityUnits,totalValue,orderValueCurrency,lineCount,totalShippedQuantity,exclude,sourceLink,precio_unitario,precio_unitario_iva
19,1.000567e+09,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,320.0,EA,34560.0,USD,1.0,NaN,NaN,http://lighttree.com/1000567425,108.0,128.52
42,1.000567e+09,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-1,NaN,2021-07-15T00:00:00,2021-07-22T00:00:00,2021-07-26T00:00:00,...,44.0,EA,4752.0,USD,1.0,NaN,NaN,http://lighttree.com/1000567251,108.0,128.52
61,1.000567e+09,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-1,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,124.0,EA,13392.0,USD,1.0,NaN,NaN,http://lighttree.com/1000567332,108.0,128.52
64,1.000567e+09,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-1,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,512.0,EA,48640.0,USD,1.0,NaN,NaN,http://lighttree.com/1000567338,95.0,113.05
75,1.000567e+09,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-1,NaN,2021-07-08T00:00:00,2021-07-15T00:00:00,2021-07-19T00:00:00,...,56.0,EA,5320.0,USD,1.0,NaN,NaN,http://lighttree.com/1000567370,95.0,113.05
102,1.000567e+09,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-1,NaN,2021-06-29T00:00:00,2021-07-06T00:00:00,2021-07-10T00:00:00,...,75.0,EA,8100.0,USD,1.0,NaN,NaN,http://lighttree.com/1000567463,108.0,128.52
135,1.000567e+09,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,124.0,EA,13392.0,USD,1.0,NaN,NaN,http://lighttree.com/1000567230,108.0,128.52
157,1.000567e+09,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,320.0,EA,34560.0,USD,1.0,NaN,NaN,http://lighttree.com/1000567315,108.0,128.52

**Filtrado loc e iloc:**

- ```loc:``` Se utiliza para seleccionar filas y columnas por etiquetas (nombres de filas y columnas).

- ```iloc:``` Se utiliza para seleccionar filas y columnas por índices numéricos (posición).

___loc___

Me sirve para acceder por medio de filtros sobre las filas o por el indice especifico

In [40]:
datos_excel.loc[datos_excel['vendor.organizationIdentifier'] == 'SilverOptics']

,orderIdentifier,orderType,vendor.organizationIdentifier,buyer.organizationIdentifier,shipFromInstructionLocation.locationIdentifier,shipToLocation.locationIdentifier,orderStatus,createdDate,requestedShipDate,requestedDeliveryDate,...,quantity,quantityUnits,totalValue,orderValueCurrency,lineCount,totalShippedQuantity,exclude,sourceLink,precio_unitario,precio_unitario_iva
19,1000567425,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,320,EA,34560,USD,1,NaN,NaN,http://lighttree.com/1000567425,108.0,128.52
42,1000567251,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-1,NaN,2021-07-15T00:00:00,2021-07-22T00:00:00,2021-07-26T00:00:00,...,44,EA,4752,USD,1,NaN,NaN,http://lighttree.com/1000567251,108.0,128.52
61,1000567332,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-1,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,124,EA,13392,USD,1,NaN,NaN,http://lighttree.com/1000567332,108.0,128.52
64,1000567338,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-1,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,512,EA,48640,USD,1,NaN,NaN,http://lighttree.com/1000567338,95.0,113.05
75,1000567370,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-1,NaN,2021-07-08T00:00:00,2021-07-15T00:00:00,2021-07-19T00:00:00,...,56,EA,5320,USD,1,NaN,NaN,http://lighttree.com/1000567370,95.0,113.05
102,1000567463,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-1,NaN,2021-06-29T00:00:00,2021-07-06T00:00:00,2021-07-10T00:00:00,...,75,EA,8100,USD,1,NaN,NaN,http://lighttree.com/1000567463,108.0,128.52
135,1000567230,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,124,EA,13392,USD,1,NaN,NaN,http://lighttree.com/1000567230,108.0,128.52
157,1000567315,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,320,EA,34560,USD,1,NaN,NaN,http://lighttree.com/1000567315,108.0,128.52

In [41]:
datos_excel.loc[(datos_excel['vendor.organizationIdentifier'] == 'SilverOptics') & (datos_excel['quantity'] > 200)]

,orderIdentifier,orderType,vendor.organizationIdentifier,buyer.organizationIdentifier,shipFromInstructionLocation.locationIdentifier,shipToLocation.locationIdentifier,orderStatus,createdDate,requestedShipDate,requestedDeliveryDate,...,quantity,quantityUnits,totalValue,orderValueCurrency,lineCount,totalShippedQuantity,exclude,sourceLink,precio_unitario,precio_unitario_iva
19,1000567425,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,320,EA,34560,USD,1,NaN,NaN,http://lighttree.com/1000567425,108.0,128.52
64,1000567338,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-1,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,512,EA,48640,USD,1,NaN,NaN,http://lighttree.com/1000567338,95.0,113.05
157,1000567315,INBOUND,SilverOptics,LightTree,SilverOptics - Dover,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,...,320,EA,34560,USD,1,NaN,NaN,http://lighttree.com/1000567315,108.0,128.52

In [42]:
datos_excel.loc[0:4,['orderIdentifier', 'orderType', 'vendor.organizationIdentifier']]

   orderIdentifier orderType vendor.organizationIdentifier
0       1000567495   INBOUND                         F & M
1       1000567490   INBOUND                       Luminar
2       1000567484   INBOUND                      Flexilux
3       1000567483   INBOUND                       Brewers
4       1000567481   INBOUND                        McGrey

In [43]:
datos_excel.iloc[:,0:3]

     orderIdentifier orderType vendor.organizationIdentifier
0         1000567495   INBOUND                         F & M
1         1000567490   INBOUND                       Luminar
2         1000567484   INBOUND                      Flexilux
3         1000567483   INBOUND                       Brewers
4         1000567481   INBOUND                        McGrey
..               ...       ...                           ...
163       1000567351   INBOUND                  Total Source
164       1000567364   INBOUND                       Mueller
165       1000567374   INBOUND                            EM
166       1000567376   INBOUND                        Ripley
167       1000567378   INBOUND                    Interalloy

[168 rows x 3 columns]

___iloc___

Me sirve para acceder a las filas por la posicion en donde se encuentran

In [44]:
datos_excel.set_index('orderIdentifier', inplace=True)

In [45]:
datos_excel

,orderType,vendor.organizationIdentifier,buyer.organizationIdentifier,shipFromInstructionLocation.locationIdentifier,shipToLocation.locationIdentifier,orderStatus,createdDate,requestedShipDate,requestedDeliveryDate,plannedShipDate,...,quantity,quantityUnits,totalValue,orderValueCurrency,lineCount,totalShippedQuantity,exclude,sourceLink,precio_unitario,precio_unitario_iva
orderIdentifier,,,,,,,,,,,,,,,,,,,,,
1000567495,INBOUND,F & M,LightTree,F & M - Columbus,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,124,EA,6200,USD,1,NaN,NaN,http://lighttree.com/1000567495,50.0,59.50
1000567490,INBOUND,Luminar,LightTree,Luminar - Palm Beach Gardens,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,124,EA,117800,USD,1,NaN,NaN,http://lighttree.com/1000567490,950.0,1130.50
1000567484,INBOUND,Flexilux,LightTree,Flexilux - Worcester,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,124,EA,569408,USD,1,NaN,NaN,http://lighttree.com/1000567484,4592.0,5464.48
1000567483,INBOUND,Brewers,LightTree,Brewers - Phoenix,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,124,EA,159588,USD,1,NaN,NaN,http://lighttree.com/1000567483,1287.0,1531.53
1000567481,INBOUND,McGrey,LightTree,McGrey - Mt Sterling,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,320,EA,316800,USD,1,NaN,NaN,http://lighttree.com/1000567481,990.0,1178.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000567351,INBOUND,Total Source,LightTree,Total Source - Waukesha,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,124,EA,121024,USD,1,NaN,NaN,http://lighttree.com/1000567351,976.0,1161.44
1000567364,INBOUND,Mueller,LightTree,Mueller - Pittsburgh,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,320,EA,135040,USD,1,NaN,NaN,http://lighttree.com/1000567364,422.0,502.18
1000567374,INBOUND,EM,LightTree,EM - Hemphill,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,320,EA,6080,USD,1,NaN,NaN,http://lighttree.com/1000567374,19.0,22.61
1000567376,INBOUND,Ripley,LightTree,Ripley - Trenton,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,320,EA,112000,USD,1,NaN,NaN,http://lighttree.com/1000567376,350.0,416.50
1000567378,INBOUND,Interalloy,LightTree,Interalloy - Bozeman,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,124,EA,620,USD,1,NaN,NaN,http://lighttree.com/1000567378,5.0,5.95

In [46]:
datos_excel.iloc[0:10]

,orderType,vendor.organizationIdentifier,buyer.organizationIdentifier,shipFromInstructionLocation.locationIdentifier,shipToLocation.locationIdentifier,orderStatus,createdDate,requestedShipDate,requestedDeliveryDate,plannedShipDate,...,quantity,quantityUnits,totalValue,orderValueCurrency,lineCount,totalShippedQuantity,exclude,sourceLink,precio_unitario,precio_unitario_iva
orderIdentifier,,,,,,,,,,,,,,,,,,,,,
1000567495,INBOUND,F & M,LightTree,F & M - Columbus,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,124,EA,6200,USD,1,NaN,NaN,http://lighttree.com/1000567495,50.0,59.50
1000567490,INBOUND,Luminar,LightTree,Luminar - Palm Beach Gardens,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,124,EA,117800,USD,1,NaN,NaN,http://lighttree.com/1000567490,950.0,1130.50
1000567484,INBOUND,Flexilux,LightTree,Flexilux - Worcester,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,124,EA,569408,USD,1,NaN,NaN,http://lighttree.com/1000567484,4592.0,5464.48
1000567483,INBOUND,Brewers,LightTree,Brewers - Phoenix,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,124,EA,159588,USD,1,NaN,NaN,http://lighttree.com/1000567483,1287.0,1531.53
1000567481,INBOUND,McGrey,LightTree,McGrey - Mt Sterling,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,320,EA,316800,USD,1,NaN,NaN,http://lighttree.com/1000567481,990.0,1178.10
1000567478,INBOUND,Total Source,LightTree,Total Source - Waukesha,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,320,EA,312320,USD,1,NaN,NaN,http://lighttree.com/1000567478,976.0,1161.44
1000567477,INBOUND,Hardy,LightTree,Hardy - Salina,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,320,EA,7680,USD,1,NaN,NaN,http://lighttree.com/1000567477,24.0,28.56
1000567476,INBOUND,EM,LightTree,EM - Hemphill,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,320,EA,6080,USD,1,NaN,NaN,http://lighttree.com/1000567476,19.0,22.61
1000567473,INBOUND,McGrey,LightTree,McGrey - Mt Sterling,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,124,EA,180048,USD,1,NaN,NaN,http://lighttree.com/1000567473,1452.0,1727.88
1000567468,INBOUND,Mueller,LightTree,Mueller - Pittsburgh,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,320,EA,131840,USD,1,NaN,NaN,http://lighttree.com/1000567468,412.0,490.28

### 3.5. Agregar columnas

In [47]:
## Agregar un valor unico a todas las filas de una columna
datos_excel['valor_unico'] = 'HOLAAAA'
datos_excel

,orderType,vendor.organizationIdentifier,buyer.organizationIdentifier,shipFromInstructionLocation.locationIdentifier,shipToLocation.locationIdentifier,orderStatus,createdDate,requestedShipDate,requestedDeliveryDate,plannedShipDate,...,quantityUnits,totalValue,orderValueCurrency,lineCount,totalShippedQuantity,exclude,sourceLink,precio_unitario,precio_unitario_iva,valor_unico
orderIdentifier,,,,,,,,,,,,,,,,,,,,,
1000567495,INBOUND,F & M,LightTree,F & M - Columbus,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,EA,6200,USD,1,NaN,NaN,http://lighttree.com/1000567495,50.0,59.50,HOLAAAA
1000567490,INBOUND,Luminar,LightTree,Luminar - Palm Beach Gardens,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,EA,117800,USD,1,NaN,NaN,http://lighttree.com/1000567490,950.0,1130.50,HOLAAAA
1000567484,INBOUND,Flexilux,LightTree,Flexilux - Worcester,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,EA,569408,USD,1,NaN,NaN,http://lighttree.com/1000567484,4592.0,5464.48,HOLAAAA
1000567483,INBOUND,Brewers,LightTree,Brewers - Phoenix,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,EA,159588,USD,1,NaN,NaN,http://lighttree.com/1000567483,1287.0,1531.53,HOLAAAA
1000567481,INBOUND,McGrey,LightTree,McGrey - Mt Sterling,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,EA,316800,USD,1,NaN,NaN,http://lighttree.com/1000567481,990.0,1178.10,HOLAAAA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000567351,INBOUND,Total Source,LightTree,Total Source - Waukesha,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,EA,121024,USD,1,NaN,NaN,http://lighttree.com/1000567351,976.0,1161.44,HOLAAAA
1000567364,INBOUND,Mueller,LightTree,Mueller - Pittsburgh,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,EA,135040,USD,1,NaN,NaN,http://lighttree.com/1000567364,422.0,502.18,HOLAAAA
1000567374,INBOUND,EM,LightTree,EM - Hemphill,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,EA,6080,USD,1,NaN,NaN,http://lighttree.com/1000567374,19.0,22.61,HOLAAAA
1000567376,INBOUND,Ripley,LightTree,Ripley - Trenton,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,EA,112000,USD,1,NaN,NaN,http://lighttree.com/1000567376,350.0,416.50,HOLAAAA
1000567378,INBOUND,Interalloy,LightTree,Interalloy - Bozeman,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,EA,620,USD,1,NaN,NaN,http://lighttree.com/1000567378,5.0,5.95,HOLAAAA

In [48]:
## Agregar una columna calculada a partir de otras columnas
datos_excel['total_value_iva'] = datos_excel['precio_unitario_iva'] * datos_excel['quantity']
datos_excel

,orderType,vendor.organizationIdentifier,buyer.organizationIdentifier,shipFromInstructionLocation.locationIdentifier,shipToLocation.locationIdentifier,orderStatus,createdDate,requestedShipDate,requestedDeliveryDate,plannedShipDate,...,totalValue,orderValueCurrency,lineCount,totalShippedQuantity,exclude,sourceLink,precio_unitario,precio_unitario_iva,valor_unico,total_value_iva
orderIdentifier,,,,,,,,,,,,,,,,,,,,,
1000567495,INBOUND,F & M,LightTree,F & M - Columbus,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,6200,USD,1,NaN,NaN,http://lighttree.com/1000567495,50.0,59.50,HOLAAAA,7378.00
1000567490,INBOUND,Luminar,LightTree,Luminar - Palm Beach Gardens,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,117800,USD,1,NaN,NaN,http://lighttree.com/1000567490,950.0,1130.50,HOLAAAA,140182.00
1000567484,INBOUND,Flexilux,LightTree,Flexilux - Worcester,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,569408,USD,1,NaN,NaN,http://lighttree.com/1000567484,4592.0,5464.48,HOLAAAA,677595.52
1000567483,INBOUND,Brewers,LightTree,Brewers - Phoenix,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,159588,USD,1,NaN,NaN,http://lighttree.com/1000567483,1287.0,1531.53,HOLAAAA,189909.72
1000567481,INBOUND,McGrey,LightTree,McGrey - Mt Sterling,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,316800,USD,1,NaN,NaN,http://lighttree.com/1000567481,990.0,1178.10,HOLAAAA,376992.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000567351,INBOUND,Total Source,LightTree,Total Source - Waukesha,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,121024,USD,1,NaN,NaN,http://lighttree.com/1000567351,976.0,1161.44,HOLAAAA,144018.56
1000567364,INBOUND,Mueller,LightTree,Mueller - Pittsburgh,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,135040,USD,1,NaN,NaN,http://lighttree.com/1000567364,422.0,502.18,HOLAAAA,160697.60
1000567374,INBOUND,EM,LightTree,EM - Hemphill,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,6080,USD,1,NaN,NaN,http://lighttree.com/1000567374,19.0,22.61,HOLAAAA,7235.20
1000567376,INBOUND,Ripley,LightTree,Ripley - Trenton,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,112000,USD,1,NaN,NaN,http://lighttree.com/1000567376,350.0,416.50,HOLAAAA,133280.00
1000567378,INBOUND,Interalloy,LightTree,Interalloy - Bozeman,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,620,USD,1,NaN,NaN,http://lighttree.com/1000567378,5.0,5.95,HOLAAAA,737.80

In [49]:
def extraer_ubicacion(locationIdentifier):
    resultado = locationIdentifier.split('-')
    i = 0
    while i < len(resultado):
        valor = resultado[i]
        ## Strip me sirve para quitar los espacios en blanco al principio y al final de cada valor
        valor = valor.strip()
        resultado[i] = valor
        i += 1
        
    return resultado[1]

In [50]:
extraer_ubicacion('AHTD - Bentonville')

'Bentonville'

In [51]:
## Agregar una columna calculada a partir de otras columnas utilizando una funcion personalizada con apply
datos_excel['ubicacion'] = datos_excel['shipToLocation.locationIdentifier'].apply(extraer_ubicacion)
datos_excel

,orderType,vendor.organizationIdentifier,buyer.organizationIdentifier,shipFromInstructionLocation.locationIdentifier,shipToLocation.locationIdentifier,orderStatus,createdDate,requestedShipDate,requestedDeliveryDate,plannedShipDate,...,orderValueCurrency,lineCount,totalShippedQuantity,exclude,sourceLink,precio_unitario,precio_unitario_iva,valor_unico,total_value_iva,ubicacion
orderIdentifier,,,,,,,,,,,,,,,,,,,,,
1000567495,INBOUND,F & M,LightTree,F & M - Columbus,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,USD,1,NaN,NaN,http://lighttree.com/1000567495,50.0,59.50,HOLAAAA,7378.00,2
1000567490,INBOUND,Luminar,LightTree,Luminar - Palm Beach Gardens,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,USD,1,NaN,NaN,http://lighttree.com/1000567490,950.0,1130.50,HOLAAAA,140182.00,2
1000567484,INBOUND,Flexilux,LightTree,Flexilux - Worcester,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,USD,1,NaN,NaN,http://lighttree.com/1000567484,4592.0,5464.48,HOLAAAA,677595.52,2
1000567483,INBOUND,Brewers,LightTree,Brewers - Phoenix,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,USD,1,NaN,NaN,http://lighttree.com/1000567483,1287.0,1531.53,HOLAAAA,189909.72,2
1000567481,INBOUND,McGrey,LightTree,McGrey - Mt Sterling,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,USD,1,NaN,NaN,http://lighttree.com/1000567481,990.0,1178.10,HOLAAAA,376992.00,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000567351,INBOUND,Total Source,LightTree,Total Source - Waukesha,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,USD,1,NaN,NaN,http://lighttree.com/1000567351,976.0,1161.44,HOLAAAA,144018.56,2
1000567364,INBOUND,Mueller,LightTree,Mueller - Pittsburgh,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,USD,1,NaN,NaN,http://lighttree.com/1000567364,422.0,502.18,HOLAAAA,160697.60,2
1000567374,INBOUND,EM,LightTree,EM - Hemphill,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,USD,1,NaN,NaN,http://lighttree.com/1000567374,19.0,22.61,HOLAAAA,7235.20,2
1000567376,INBOUND,Ripley,LightTree,Ripley - Trenton,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,USD,1,NaN,NaN,http://lighttree.com/1000567376,350.0,416.50,HOLAAAA,133280.00,2
1000567378,INBOUND,Interalloy,LightTree,Interalloy - Bozeman,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,USD,1,NaN,NaN,http://lighttree.com/1000567378,5.0,5.95,HOLAAAA,737.80,2

### 3.6. Eliminar columnas

In [52]:
datos_excel.drop(columns=["valor_unico"], inplace=True)
datos_excel.head()

,orderType,vendor.organizationIdentifier,buyer.organizationIdentifier,shipFromInstructionLocation.locationIdentifier,shipToLocation.locationIdentifier,orderStatus,createdDate,requestedShipDate,requestedDeliveryDate,plannedShipDate,...,totalValue,orderValueCurrency,lineCount,totalShippedQuantity,exclude,sourceLink,precio_unitario,precio_unitario_iva,total_value_iva,ubicacion
orderIdentifier,,,,,,,,,,,,,,,,,,,,,
1000567495,INBOUND,F & M,LightTree,F & M - Columbus,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,6200,USD,1,NaN,NaN,http://lighttree.com/1000567495,50.0,59.50,7378.00,2
1000567490,INBOUND,Luminar,LightTree,Luminar - Palm Beach Gardens,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,117800,USD,1,NaN,NaN,http://lighttree.com/1000567490,950.0,1130.50,140182.00,2
1000567484,INBOUND,Flexilux,LightTree,Flexilux - Worcester,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,569408,USD,1,NaN,NaN,http://lighttree.com/1000567484,4592.0,5464.48,677595.52,2
1000567483,INBOUND,Brewers,LightTree,Brewers - Phoenix,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,159588,USD,1,NaN,NaN,http://lighttree.com/1000567483,1287.0,1531.53,189909.72,2
1000567481,INBOUND,McGrey,LightTree,McGrey - Mt Sterling,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,316800,USD,1,NaN,NaN,http://lighttree.com/1000567481,990.0,1178.10,376992.00,2

In [53]:
## Alterar orden de las columnas

datos_excel.head()
datos_excel_2 = datos_excel[['orderType',	'vendor.organizationIdentifier',	'shipFromInstructionLocation.locationIdentifier',	'buyer.organizationIdentifier', 'shipToLocation.locationIdentifier',	'orderStatus',	'createdDate','requestedShipDate','requestedDeliveryDate' , 'quantityUnits','totalValue','orderValueCurrency','lineCount','totalShippedQuantity','exclude','sourceLink','precio_unitario','precio_unitario_iva','total_value_iva']]
datos_excel_2.head()

,orderType,vendor.organizationIdentifier,shipFromInstructionLocation.locationIdentifier,buyer.organizationIdentifier,shipToLocation.locationIdentifier,orderStatus,createdDate,requestedShipDate,requestedDeliveryDate,quantityUnits,totalValue,orderValueCurrency,lineCount,totalShippedQuantity,exclude,sourceLink,precio_unitario,precio_unitario_iva,total_value_iva
orderIdentifier,,,,,,,,,,,,,,,,,,,
1000567495,INBOUND,F & M,F & M - Columbus,LightTree,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,EA,6200,USD,1,NaN,NaN,http://lighttree.com/1000567495,50.0,59.50,7378.00
1000567490,INBOUND,Luminar,Luminar - Palm Beach Gardens,LightTree,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,EA,117800,USD,1,NaN,NaN,http://lighttree.com/1000567490,950.0,1130.50,140182.00
1000567484,INBOUND,Flexilux,Flexilux - Worcester,LightTree,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,EA,569408,USD,1,NaN,NaN,http://lighttree.com/1000567484,4592.0,5464.48,677595.52
1000567483,INBOUND,Brewers,Brewers - Phoenix,LightTree,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,EA,159588,USD,1,NaN,NaN,http://lighttree.com/1000567483,1287.0,1531.53,189909.72
1000567481,INBOUND,McGrey,McGrey - Mt Sterling,LightTree,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,EA,316800,USD,1,NaN,NaN,http://lighttree.com/1000567481,990.0,1178.10,376992.00

### 3.7. Quitar duplicados

In [54]:
## Comprobar que existen duplicados en una columna
datos_excel.duplicated(subset=['orderType'])

orderIdentifier
1000567495    False
1000567490     True
1000567484     True
1000567483     True
1000567481     True
              ...
1000567351     True
1000567364     True
1000567374     True
1000567376     True
1000567378     True
Length: 168, dtype: bool

In [55]:
datos_excel[['orderType','vendor.organizationIdentifier']]

                orderType vendor.organizationIdentifier
orderIdentifier
1000567495        INBOUND                         F & M
1000567490        INBOUND                       Luminar
1000567484        INBOUND                      Flexilux
1000567483        INBOUND                       Brewers
1000567481        INBOUND                        McGrey
...                   ...                           ...
1000567351        INBOUND                  Total Source
1000567364        INBOUND                       Mueller
1000567374        INBOUND                            EM
1000567376        INBOUND                        Ripley
1000567378        INBOUND                    Interalloy

[168 rows x 2 columns]

In [56]:
## Comprobar que existen duplicados en multiples columnas
datos_excel.duplicated(subset=['orderType','vendor.organizationIdentifier'])

orderIdentifier
1000567495    False
1000567490    False
1000567484    False
1000567483    False
1000567481    False
              ...
1000567351     True
1000567364     True
1000567374     True
1000567376     True
1000567378     True
Length: 168, dtype: bool

In [57]:
## Suma los duplicados --> 0 siginifica que no hay filas duplicadas en el DataFrame
datos_excel.duplicated().sum()

np.int64(0)

In [58]:
## Borrar duplicados del DataFrame
datos_excel.drop_duplicates(inplace=True)

In [59]:
datos_excel_inbound = datos_excel[datos_excel['orderType'] == 'INBOUND']

In [60]:
datos_excel_inbound

,orderType,vendor.organizationIdentifier,buyer.organizationIdentifier,shipFromInstructionLocation.locationIdentifier,shipToLocation.locationIdentifier,orderStatus,createdDate,requestedShipDate,requestedDeliveryDate,plannedShipDate,...,totalValue,orderValueCurrency,lineCount,totalShippedQuantity,exclude,sourceLink,precio_unitario,precio_unitario_iva,total_value_iva,ubicacion
orderIdentifier,,,,,,,,,,,,,,,,,,,,,
1000567495,INBOUND,F & M,LightTree,F & M - Columbus,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,6200,USD,1,NaN,NaN,http://lighttree.com/1000567495,50.0,59.50,7378.00,2
1000567490,INBOUND,Luminar,LightTree,Luminar - Palm Beach Gardens,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,117800,USD,1,NaN,NaN,http://lighttree.com/1000567490,950.0,1130.50,140182.00,2
1000567484,INBOUND,Flexilux,LightTree,Flexilux - Worcester,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,569408,USD,1,NaN,NaN,http://lighttree.com/1000567484,4592.0,5464.48,677595.52,2
1000567483,INBOUND,Brewers,LightTree,Brewers - Phoenix,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,159588,USD,1,NaN,NaN,http://lighttree.com/1000567483,1287.0,1531.53,189909.72,2
1000567481,INBOUND,McGrey,LightTree,McGrey - Mt Sterling,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,316800,USD,1,NaN,NaN,http://lighttree.com/1000567481,990.0,1178.10,376992.00,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000567351,INBOUND,Total Source,LightTree,Total Source - Waukesha,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,121024,USD,1,NaN,NaN,http://lighttree.com/1000567351,976.0,1161.44,144018.56,2
1000567364,INBOUND,Mueller,LightTree,Mueller - Pittsburgh,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,135040,USD,1,NaN,NaN,http://lighttree.com/1000567364,422.0,502.18,160697.60,2
1000567374,INBOUND,EM,LightTree,EM - Hemphill,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,6080,USD,1,NaN,NaN,http://lighttree.com/1000567374,19.0,22.61,7235.20,2
1000567376,INBOUND,Ripley,LightTree,Ripley - Trenton,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,112000,USD,1,NaN,NaN,http://lighttree.com/1000567376,350.0,416.50,133280.00,2
1000567378,INBOUND,Interalloy,LightTree,Interalloy - Bozeman,LT-2,NaN,2021-06-16T00:00:00,2021-06-23T00:00:00,2021-06-27T00:00:00,2021-06-23T00:00:00,...,620,USD,1,NaN,NaN,http://lighttree.com/1000567378,5.0,5.95,737.80,2

### 3.8. Agrupar datos

In [61]:
## Agrupacion sencilla por una columna y calculo de la media de otra columna
datos_excel.groupby('orderType')['totalValue'].mean()

orderType
INBOUND    106157.785714
Name: totalValue, dtype: float64

In [62]:
## Agrupacion por varias columnas y calculo de la media de varios datos de valores distintos
datos_excel.groupby(['orderType','buyer.organizationIdentifier'])[['quantity','totalValue']].mean()

                                          quantity     totalValue
orderType buyer.organizationIdentifier
INBOUND   LightTree                     283.410714  106157.785714

### 3.9. Merge

![Diagrama de JOINs en SQL](https://www.hostingplus.com.co/wp-content/uploads/2021/06/JOIN.jpg)

In [63]:
catalogo = pd.read_excel('archivo_excel.xlsx', sheet_name='Catalogo')

In [64]:
catalogo

,buyer.organizationIdentifier,publicName,creationDate
0,AHTD,Apex Highway Technologies Division,2026-04-06
1,CALTRAN,CalTranscend Systems,2025-01-10
2,COLA,Core Logistics Alliance,2024-11-18
3,FAA,Flight Axis Authority,2025-02-22
4,KYTC,Kinetic Transit Core,2023-11-29
5,LightTree,LightTree Innovations,2023-10-07
6,MAHD,Meridian Advanced Highway Division,2024-01-11
7,NYDOT,New York Digital Operations Transit,2022-10-17
8,CAT,Gatos asociados SA,2022-07-14

In [65]:
merge_ordenes_catalogo = datos_excel.merge(catalogo, left_on ='buyer.organizationIdentifier', right_on='buyer.organizationIdentifier', how='inner')

In [66]:
merge_ordenes_catalogo[(merge_ordenes_catalogo['buyer.organizationIdentifier'] == 'CAT')| (merge_ordenes_catalogo['buyer.organizationIdentifier'] == 'QPWD')]

Empty DataFrame
Columns: [orderType, vendor.organizationIdentifier, buyer.organizationIdentifier, shipFromInstructionLocation.locationIdentifier, shipToLocation.locationIdentifier, orderStatus, createdDate, requestedShipDate, requestedDeliveryDate, plannedShipDate, plannedDeliveryDate, quantity, quantityUnits, totalValue, orderValueCurrency, lineCount, totalShippedQuantity, exclude, sourceLink, precio_unitario, precio_unitario_iva, total_value_iva, ubicacion, publicName, creationDate]
Index: []

[0 rows x 25 columns]

In [67]:
merge_ordenes_catalogo = datos_excel.merge(catalogo, left_on ='buyer.organizationIdentifier', right_on='buyer.organizationIdentifier', how='left')

In [68]:
merge_ordenes_catalogo[(merge_ordenes_catalogo['buyer.organizationIdentifier'] == 'CAT')| (merge_ordenes_catalogo['buyer.organizationIdentifier'] == 'QPWD')]

Empty DataFrame
Columns: [orderType, vendor.organizationIdentifier, buyer.organizationIdentifier, shipFromInstructionLocation.locationIdentifier, shipToLocation.locationIdentifier, orderStatus, createdDate, requestedShipDate, requestedDeliveryDate, plannedShipDate, plannedDeliveryDate, quantity, quantityUnits, totalValue, orderValueCurrency, lineCount, totalShippedQuantity, exclude, sourceLink, precio_unitario, precio_unitario_iva, total_value_iva, ubicacion, publicName, creationDate]
Index: []

[0 rows x 25 columns]

In [69]:
merge_ordenes_catalogo = datos_excel.merge(catalogo, left_on ='buyer.organizationIdentifier', right_on='buyer.organizationIdentifier', how='right')
merge_ordenes_catalogo[['vendor.organizationIdentifier', 'buyer.organizationIdentifier', 'publicName']]

,vendor.organizationIdentifier,buyer.organizationIdentifier,publicName
0,NaN,AHTD,Apex Highway Technologies Division
1,NaN,CALTRAN,CalTranscend Systems
2,NaN,COLA,Core Logistics Alliance
3,NaN,FAA,Flight Axis Authority
4,NaN,KYTC,Kinetic Transit Core
...,...,...,...
171,Ripley,LightTree,LightTree Innovations
172,Interalloy,LightTree,LightTree Innovations
173,NaN,MAHD,Meridian Advanced Highway Division
174,NaN,NYDOT,New York Digital Operations Transit
175,NaN,CAT,Gatos asociados SA

In [70]:
merge_ordenes_catalogo[(merge_ordenes_catalogo['buyer.organizationIdentifier'] == 'CAT')| (merge_ordenes_catalogo['buyer.organizationIdentifier'] == 'QPWD')]

,orderType,vendor.organizationIdentifier,buyer.organizationIdentifier,shipFromInstructionLocation.locationIdentifier,shipToLocation.locationIdentifier,orderStatus,createdDate,requestedShipDate,requestedDeliveryDate,plannedShipDate,...,lineCount,totalShippedQuantity,exclude,sourceLink,precio_unitario,precio_unitario_iva,total_value_iva,ubicacion,publicName,creationDate
175,NaN,NaN,CAT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Gatos asociados SA,2022-07-14

### 4. Exportar

In [71]:
merge_ordenes_catalogo.to_csv('merge_ordenes_catalogo.csv')

In [72]:
merge_ordenes_catalogo.to_csv('merge_ordenes_catalogo.csv', index=False)

In [73]:
merge_ordenes_catalogo.to_excel('merge_ordenes_catalogo.xlsx', index=False)

In [74]:
merge_ordenes_catalogo.to_html('merge_ordenes_catalogo.html', index=False)

### Otras funcionalidades

| **Tema**                        | **Descripción**                                                                 | **Funciones/Métodos Clave**                     | **Ejemplo y Resultado**                                                                 |
|----------------------------------|---------------------------------------------------------------------------------|-------------------------------------------------|-----------------------------------------------------------------------------------------|
| **Manejo de Datos Faltantes**    | Identificar, eliminar o rellenar datos faltantes.                               | `isna()`, `dropna()`, `fillna()`, `interpolate()`| ```df["columna"].fillna(df["columna"].mean(), inplace=True)```<br>**Resultado:** Rellena los valores faltantes con la media. |
| **Aplicar Funciones**            | Aplicar funciones personalizadas a columnas o filas.                            | `apply()`, `map()`, `applymap()`                | ```df["columna"] = df["columna"].apply(lambda x: x * 2)```<br>**Resultado:** Multiplica cada valor por 2. |
| **Ordenar Datos**                | Ordenar DataFrames por columnas o índices.                                      | `sort_values()`, `sort_index()`                 | ```df.sort_values("Value", ascending=False)```<br>**Resultado:** Ordena por "Value" de forma descendente. |
| **Pivot Tables**                 | Crear tablas dinámicas para resumir datos.                                      | `pivot_table()`                                | ```df.pivot_table(values="Value", index="Country Name", columns="Year", aggfunc="sum")```<br>**Resultado:** Tabla dinámica con la suma de "Value" por país y año. |
| **Melt y Pivot**                 | Transformar DataFrames entre formatos largo y ancho.                            | `melt()`, `pivot()`                            | ```df.melt(id_vars=["Country Name", "Year"], value_vars=["Value", "Value_2"])```<br>**Resultado:** Convierte el DataFrame a formato largo. |
| **Concatenación de DataFrames**  | Combinar DataFrames vertical u horizontalmente.                                 | `concat()`                                     | ```pd.concat([df1, df2], axis=0)```<br>**Resultado:** Combina dos DataFrames verticalmente. |
| **Manejo de Datos de Texto**     | Manipular columnas de texto (extraer, dividir, reemplazar).                     | `str.upper()`, `str.split()`, `str.replace()`  | ```df["columna"] = df["columna"].str.upper()```<br>**Resultado:** Convierte el texto a mayúsculas. |
| **Manejo de Fechas y Tiempos**   | Trabajar con columnas de fechas y realizar operaciones temporales.              | `pd.to_datetime()`, `dt.year`, `dt.month`      | ```df["fecha"] = pd.to_datetime(df["fecha"])```<br>**Resultado:** Convierte la columna a tipo `datetime`. |
| **Manejo de Datos Categóricos**  | Convertir columnas a tipo categórico y crear variables dummy.                   | `astype("category")`, `pd.get_dummies()`       | ```df["columna"] = df["columna"].astype("category")```<br>**Resultado:** Convierte la columna a tipo categórico. |
| **Manejo de Grandes Volúmenes**  | Leer y procesar archivos grandes en bloques.                                    | `chunksize` en `read_csv()`                    | ```for chunk in pd.read_csv("archivo.csv", chunksize=1000): procesar(chunk)```<br>**Resultado:** Lee el archivo en bloques de 1000 filas. |
| **Exportación de Datos**         | Guardar DataFrames en diferentes formatos (CSV, Excel, JSON, etc.).             | `to_csv()`, `to_excel()`, `to_json()`          | ```df.to_csv("datos.csv", index=False)```<br>**Resultado:** Guarda el DataFrame en un archivo CSV. |
| **Visualización de Datos**       | Crear gráficos directamente desde pandas.                                       | `plot()`, `hist()`, `boxplot()`                | ```df.plot(x="Year", y="Value", kind="line")```<br>**Resultado:** Genera un gráfico de líneas. |
| **Optimización de Código**       | Evitar bucles y usar operaciones vectorizadas.                                  | `eval()`, `query()`                            | ```df.query("Value > 1000000")```<br>**Resultado:** Filtra filas donde "Value" es mayor a 1,000,000. |
| **Trabajo con Multi-Index**      | Crear y manipular DataFrames con múltiples niveles de índice.                   | `set_index()`, `stack()`, `unstack()`          | ```df.set_index(["Country Name", "Year"])```<br>**Resultado:** Crea un DataFrame con Multi-Index. |
| **Casos Prácticos y Proyectos**  | Ejercicios y proyectos para aplicar lo aprendido en datasets reales.            | -                                              | **Ejemplo:** Análisis de ventas mensuales.<br>**Resultado:** Informe con insights clave. |